language: python
sudo: false
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - python setup.py install
  - pip install coverage
script:
  - nosetests --with-coverage --cover-package=pyfluminus
after_success:
  - coveralls